--ALTER SESSION SET nls_date_format = 'DD-MM-YYYY HH24:MI:SS';

/**********************************************
                TABLESPACE
**********************************************/
CREATE TABLESPACE "PROYECTO" LOGGING
DATAFILE 'C:\db2_2s2020\PROYECTO.dbf' SIZE 100M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

--SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE FROM DBA_USERS
--WHERE DEFAULT_TABLESPACE='PROYECTO';

--SELECT * FROM DBA_TABLESPACES;

/**********************************************
                USR_OWNER
**********************************************/
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER "USR_OWNER" IDENTIFIED BY "123"
DEFAULT TABLESPACE "PROYECTO"
QUOTA UNLIMITED ON PROYECTO;

GRANT ALL PRIVILEGES TO "USR_OWNER";

--DROP USER USR_OWNER CASCADE;
--SELECT * FROM ALL_USERS WHERE USERNAME LIKE 'USR%';


CREATE TABLE HOLA  (
    NUMERO INTEGER
);

DROP TABLE HOLA;

INSERT INTO HOLA VALUES (1);
INSERT INTO HOLA VALUES (2);
INSERT INTO HOLA VALUES (3);

SELECT * FROM HOLA;

DELETE HOLA;
COMMIT;