SELECT 
  P.ID NO_PARTIDO,
  E1.NOMBRE EQ_LOCAL,
  E2.NOMBRE EQ_VISITANTE,
  R.NO_GF GOLES_LOCAL,
  R.NO_GC GOLES_VISITA
FROM EQUIPO E1, EQUIPO E2, PARTIDO P, RESULTADO R , JORNADA J, TEMPORADA T
WHERE E1.ID = P.LOCAL
AND E2.ID = P.VISITA
AND P.ID = R.PARTIDO_ID
AND P.LOCAL = R.EQUIPO_ID
AND J.ID = P.JORNADA_ID
AND T.ID = J.TEMPORADA_ID
AND T.YEAR_INI BETWEEN 1980 AND 2020
GROUP BY P.ID, E1.NOMBRE, E2.NOMBRE, R.NO_GF, R.NO_GC
ORDER BY MAX(ABS(R.NO_GF - R.NO_GC)) DESC
FETCH NEXT 10 ROWS ONLY
;